backend:
  mode: "groq"
  groq_api:
    api_key: your_groq_api_key
    vllm_model_name: "llama-3.2-90b-vision-preview"
    transcript_model_name: "whisper-large-v3-turbo"
  scaleway_vllm_api:
    base_url: https://api.scaleway.ai/v1
    api_key: your_scaleway_api_key
    vllm_model_name: "pixtral-12b-2409"
  transcript_model:
    version: "tiny"